spring:
  # datasource
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:forum"
    username: sa
    password:
  # jpa
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  # h2
  h2:
    console:
      enabled: true
      path: /h2-console

# mensagens de erro spring
server:
  error:
    include-message: always
    include-binding-errors: always